#include <kh-extra/astgen/lexer.h>
#include <kh-extra/helper.h>

const char * kh_extra_lexer_tostr_ctx_status(enum kh_lexer_status status) {
  KH_EXTRA_SET_OFFSET("KH_LEXER_STATUS_");
  if (status & KH_LEXER_STATUS_EXTENDED) return "<extended>";
  switch (status) {
    KH_EXTRA_CASE_STR(KH_LEXER_STATUS_OK);
    KH_EXTRA_CASE_STR(KH_LEXER_STATUS_MATCH);
    KH_EXTRA_CASE_STR(KH_LEXER_STATUS_PASS);
    KH_EXTRA_CASE_STR(KH_LEXER_STATUS_NOMATCH);
    KH_EXTRA_CASE_STR(KH_LEXER_STATUS_EOB);
    KH_EXTRA_CASE_STR(KH_LEXER_STATUS_UNKNOWN_WARNING);
    KH_EXTRA_CASE_STR(KH_LEXER_STATUS_CODE_PARSE_OVERFLOW);
    KH_EXTRA_CASE_STR(KH_LEXER_STATUS_UNKNOWN_ERROR);
    KH_EXTRA_CASE_STR(KH_LEXER_STATUS_UTF8_INVALID);
    KH_EXTRA_CASE_STR(KH_LEXER_STATUS_SYNTAX_ERROR);

    case KH_LEXER_STATUS_EXTENDED:
      return "<error>";
  }

  return "<invalid>";
}


const char * kh_extra_lexer_tostr_token_type(enum kh_lexer_token_type type) {
  KH_EXTRA_SET_OFFSET("KH_LEXER_TOKEN_TYPE_");
  switch (type) {
    KH_EXTRA_CASE_STR(KH_LEXER_TOKEN_TYPE_NONE);
    KH_EXTRA_CASE_STR(KH_LEXER_TOKEN_TYPE_GROUP);
    KH_EXTRA_CASE_STR(KH_LEXER_TOKEN_TYPE_SYMBOL);
    KH_EXTRA_CASE_STR(KH_LEXER_TOKEN_TYPE_IDENTIFIER);
    KH_EXTRA_CASE_STR(KH_LEXER_TOKEN_TYPE_UNUM);
    KH_EXTRA_CASE_STR(KH_LEXER_TOKEN_TYPE_IFLT);
    KH_EXTRA_CASE_STR(KH_LEXER_TOKEN_TYPE_STRING);
    KH_EXTRA_CASE_STR(KH_LEXER_TOKEN_TYPE_STRING_INTRP);
    KH_EXTRA_CASE_STR(KH_LEXER_TOKEN_TYPE_STRING_FXHSH);
    KH_EXTRA_CASE_STR(KH_LEXER_TOKEN_TYPE_WHITESPACE);
    KH_EXTRA_CASE_STR(KH_LEXER_TOKEN_TYPE_COMMENT);
  }

  return "<invalid>";
}
